In [11]:
#Setting up the requirements
apikey = '' #Correspondiente a binance
secret = '' #Correspondinte a binance

In [12]:
from binance import Client, ThreadedWebsocketManager, ThreadedDepthCacheManager
import pandas as pd
import numpy as np
import networkx as nx

In [13]:
client = Client(apikey, secret) #conectamos nuestra cuenta de binance

In [14]:
###vamos a obtener los datos para nuestro dataframe
tickers = client.get_all_tickers()
tickers_df = pd.DataFrame(tickers)
#tickers_df.set_index('symbol', inplace=True)

#tickers que vamos a usar
names = ['XRP', 'BTC', 'ETH', 'USDT', 'USDC', 'XRP', 'ADA', 'BUSD']

In [119]:
# preparamos nuestras rows
datos = []

In [120]:
def tipo_cambio():
    for name in names: # por cada tickr
        for a in range(len(names)):
                for b in range(len(tickers_df.index)): #numero de rows
                    if (name + names[a] or names[a] + name) == tickers_df.iloc[b]['symbol']:
                        datos.append(tickers_df.iloc[b])
                    else:
                        continue

In [121]:
tipo_cambio()

In [122]:
datos

[symbol        XRPBTC
 price     0.00001718
 Name: 90, dtype: object,
 symbol        XRPETH
 price     0.00023060
 Name: 91, dtype: object,
 symbol       XRPUSDT
 price     0.93150000
 Name: 308, dtype: object,
 symbol       XRPUSDC
 price     0.93230000
 Name: 424, dtype: object,
 symbol       XRPBUSD
 price     0.93220000
 Name: 637, dtype: object,
 symbol           BTCUSDT
 price     54199.88000000
 Name: 11, dtype: object,
 symbol           BTCUSDC
 price     54218.44000000
 Name: 422, dtype: object,
 symbol           BTCBUSD
 price     54234.24000000
 Name: 620, dtype: object,
 symbol        ETHBTC
 price     0.07447000
 Name: 0, dtype: object,
 symbol          ETHUSDT
 price     4036.01000000
 Name: 12, dtype: object,
 symbol          ETHUSDC
 price     4038.37000000
 Name: 423, dtype: object,
 symbol          ETHBUSD
 price     4038.41000000
 Name: 638, dtype: object,
 symbol      USDCUSDT
 price     0.99940000
 Name: 427, dtype: object,
 symbol      USDCBUSD
 price     1.00000000
 Name: 1258, dtype: object,
 symbol        XRPBTC
 price     0.00001718
 Name: 90, dtype: object,
 symbol        XRPETH
 price     0.00023060
 Name: 91, dtype: object,
 symbol       XRPUSDT
 price     0.93150000
 Name: 308, dtype: object,
 symbol       XRPUSDC
 price     0.93230000
 Name: 424, dtype: object,
 symbol       XRPBUSD
 price     0.93220000
 Name: 637, dtype: object,
 symbol        ADABTC
 price     0.00002792
 Name: 171, dtype: object,
 symbol        ADAETH
 price     0.00037480
 Name: 172, dtype: object,
 symbol       ADAUSDT
 price     1.51200000
 Name: 298, dtype: object,
 symbol       ADAUSDC
 price     1.51400000
 Name: 492, dtype: object,
 symbol       ADABUSD
 price     1.51400000
 Name: 661, dtype: object,
 symbol      BUSDUSDT
 price     0.99920000
 Name: 621, dtype: object]

In [88]:
def tipo_cambio_XRP():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'XRP' in tickers_df.iloc[i]['symbol']:
                XRP.append(tickers_df.iloc[i])
                
def tipo_cambio_BTC():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'BTC' in tickers_df.iloc[i]['symbol']:
                BTC.append(tickers_df.iloc[i])
                
def tipo_cambio_ETH():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'ETH' in tickers_df.iloc[i]['symbol']:
                ETH.append(tickers_df.iloc[i])
                
def tipo_cambio_USDT():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'USDT' in tickers_df.iloc[i]['symbol']:
                USDT.append(tickers_df.iloc[i])
                
def tipo_cambio_USDC():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'USDC' in tickers_df.iloc[i]['symbol']:
                USDC.append(tickers_df.iloc[i])
                
def tipo_cambio_ADA():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'ADA' in tickers_df.iloc[i]['symbol']:
                ADA.append(tickers_df.iloc[i])
                
def tipo_cambio_BNB():
    for i in range(tickers_df.shape[0]): #numero de rows
        if 'BNB' in tickers_df.iloc[i]['symbol']:
                BNB.append(tickers_df.iloc[i])

In [89]:
tipo_cambio_XRP()
tipo_cambio_BTC()
tipo_cambio_ETH()
tipo_cambio_USDT()
tipo_cambio_USDC()
tipo_cambio_ADA()
tipo_cambio_BNB()

[symbol        BNBBTC
 price     0.01087400
 Name: 2, dtype: object,
 symbol        BNBETH
 price     0.14600000
 Name: 10, dtype: object,
 symbol         BNBUSDT
 price     589.10000000
 Name: 98, dtype: object,
 symbol        VENBNB
 price     0.14920000
 Name: 99, dtype: object,
 symbol       YOYOBNB
 price     0.00059800
 Name: 100, dtype: object,
 symbol       POWRBNB
 price     0.00385000
 Name: 101, dtype: object,
 symbol       NULSBNB
 price     0.01257000
 Name: 106, dtype: object,
 symbol        RCNBNB
 price     0.00347300
 Name: 109, dtype: object,
 symbol        RDNBNB
 price     0.00623000
 Name: 114, dtype: object,
 symbol        DLTBNB
 price     0.00240000
 Name: 117, dtype: object,
 symbol        WTCBNB
 price     0.00180500
 Name: 118, dtype: object,
 symbol        AMBBNB
 price     0.00068500
 Name: 123, dtype: object,
 symbol         BCCBNB
 price     54.29000000
 Name: 126, dtype: object,
 symbol        BATBNB
 price     0.00183100
 Name: 129, dtype: object,
 symbol       BCPTBNB
 price     0.00116200
 Name: 132, dtype: object,
 symbol        NEOBNB
 price     0.06260000
 Name: 142, dtype: object,
 symbol        QSPBNB
 price     0.00052350
 Name: 147, dtype: object,
 symbol        BTSBNB
 price     0.00144800
 Name: 150, dtype: object,
 symbol        XZCBNB
 price     0.26750000
 Name: 153, dtype: object,
 symbol        LSKBNB
 price     0.06494000
 Name: 156, dtype: object,
 symbol       IOTABNB
 price     0.00223500
 Name: 167, dtype: object,
 symbol        ADXBNB
 price     0.00492900
 Name: 170, dtype: object,
 symbol        CMTBNB
 price     0.00057700
 Name: 177, dtype: object,
 symbol        XLMBNB
 price     0.00053920
 Name: 180, dtype: object,
 symbol        CNDBNB
 price     0.00033990
 Name: 183, dtype: object,
 symbol       WABIBNB
 price     0.00046550
 Name: 188, dtype: object,
 symbol        LTCBNB
 price     0.32540000
 Name: 191, dtype: object,
 symbol      WAVESBNB
 price     0.03195000
 Name: 196, dtype: object,
 symbol        GTOBNB
 price     0.00035200
 Name: 199, dtype: object,
 symbol        ICXBNB
 price     0.00465400
 Name: 202, dtype: object,
 symbol        OSTBNB
 price     0.00052500
 Name: 205, dtype: object,
 symbol       AIONBNB
 price     0.00261300
 Name: 210, dtype: object,
 symbol       NEBLBNB
 price     0.01356000
 Name: 213, dtype: object,
 symbol        BRDBNB
 price     0.00247000
 Name: 216, dtype: object,
 symbol        MCOBNB
 price     0.26837000
 Name: 217, dtype: object,
 symbol        NAVBNB
 price     0.00423700
 Name: 224, dtype: object,
 symbol       TRIGBNB
 price     0.01218000
 Name: 229, dtype: object,
 symbol       APPCBNB
 price     0.00189100
 Name: 232, dtype: object,
 symbol        RLCBNB
 price     0.03344000
 Name: 237, dtype: object,
 symbol       PIVXBNB
 price     0.01660000
 Name: 242, dtype: object,
 symbol      STEEMBNB
 price     0.00448000
 Name: 249, dtype: object,
 symbol       NANOBNB
 price     0.05589000
 Name: 252, dtype: object,
 symbol        VIABNB
 price     0.00958000
 Name: 255, dtype: object,
 symbol        BLZBNB
 price     0.00062190
 Name: 258, dtype: object,
 symbol         AEBNB
 price     0.00777000
 Name: 261, dtype: object,
 symbol        RPXBNB
 price     0.00145700
 Name: 264, dtype: object,
 symbol      NCASHBNB
 price     0.00006790
 Name: 267, dtype: object,
 symbol        POABNB
 price     0.00092100
 Name: 270, dtype: object,
 symbol        ZILBNB
 price     0.00013910
 Name: 273, dtype: object,
 symbol        ONTBNB
 price     0.00246200
 Name: 276, dtype: object,
 symbol      STORMBNB
 price     0.00006550
 Name: 279, dtype: object,
 symbol       QTUMBNB
 price     0.09597000
 Name: 280, dtype: object,
 symbol        XEMBNB
 price     0.00244100
 Name: 284, dtype: object,
 symbol        WANBNB
 price     0.00181000
 Name: 287, dtype: object,
 symbol        SYSBNB
 price     0.00163500
 Name: 294, dtype: object,
 symbol        QLCBNB
 price     0.00092200
 Name: 295, dtype: object,
 symbol        ADABNB
 price     0.00256800
 Name: 299, dtype: object,
 symbol        GNTBNB
 price     0.00243900
 Name: 304, dtype: object,
 symbol       LOOMBNB
 price     0.00088500
 Name: 307, dtype: object,
 symbol        BCNBNB
 price     0.00002000
 Name: 311, dtype: object,
 symbol        REPBNB
 price     0.44670000
 Name: 314, dtype: object,
 symbol       TUSDBNB
 price     0.06777000
 Name: 319, dtype: object,
 symbol        ZENBNB
 price     0.17830000
 Name: 322, dtype: object,
 symbol        SKYBNB
 price     0.03022000
 Name: 325, dtype: object,
 symbol        EOSBNB
 price     0.00650000
 Name: 327, dtype: object,
 symbol        CVCBNB
 price     0.00211200
 Name: 330, dtype: object,
 symbol      THETABNB
 price     0.01079000
 Name: 333, dtype: object,
 symbol        XRPBNB
 price     0.00158000
 Name: 334, dtype: object,
 symbol        AGIBNB
 price     0.00077200
 Name: 344, dtype: object,
 symbol        NXSBNB
 price     0.01087000
 Name: 347, dtype: object,
 symbol        ENJBNB
 price     0.00586300
 Name: 348, dtype: object,
 symbol        TRXBNB
 price     0.00015700
 Name: 352, dtype: object,
 symbol        ETCBNB
 price     0.07840000
 Name: 355, dtype: object,
 symbol         SCBNB
 price     0.00004374
 Name: 359, dtype: object,
 symbol        NASBNB
 price     0.02337000
 Name: 367, dtype: object,
 symbol        MFTBNB
 price     0.00002350
 Name: 370, dtype: object,
 symbol       ARDRBNB
 price     0.00316800
 Name: 375, dtype: object,
 symbol        VETBNB
 price     0.00018940
 Name: 382, dtype: object,
 symbol       POLYBNB
 price     0.00145900
 Name: 386, dtype: object,
 symbol        PHXBNB
 price     0.00045600
 Name: 389, dtype: object,
 symbol         GOBNB
 price     0.00069230
 Name: 393, dtype: object,
 symbol        PAXBNB
 price     0.20121000
 Name: 395, dtype: object,
 symbol        RVNBNB
 price     0.00018430
 Name: 399, dtype: object,
 symbol        DCRBNB
 price     0.78100000
 Name: 401, dtype: object,
 symbol       USDCBNB
 price     0.21755000
 Name: 402, dtype: object,
 symbol       MITHBNB
 price     0.00015280
 Name: 404, dtype: object,
 symbol          BNBPAX
 price     495.10000000
 Name: 409, dtype: object,
 symbol        RENBNB
 price     0.00458500
 Name: 416, dtype: object,
 symbol         BNBTUSD
 price     589.90000000
 Name: 417, dtype: object,
 symbol         BNBUSDC
 price     589.50000000
 Name: 421, dtype: object,
 symbol        BTTBNB
 price     0.00000525
 Name: 456, dtype: object,
 symbol        BNBUSDS
 price     22.27880000
 Name: 458, dtype: object,
 symbol        ONGBNB
 price     0.00545000
 Name: 467, dtype: object,
 symbol        HOTBNB
 price     0.00001993
 Name: 470, dtype: object,
 symbol        ZRXBNB
 price     0.01045000
 Name: 473, dtype: object,
 symbol        FETBNB
 price     0.00126000
 Name: 475, dtype: object,
 symbol        XMRBNB
 price     0.37810000
 Name: 479, dtype: object,
 symbol        ZECBNB
 price     0.39500000
 Name: 481, dtype: object,
 symbol       IOSTBNB
 price     0.00006297
 Name: 486, dtype: object,
 symbol       CELRBNB
 price     0.00018022
 Name: 488, dtype: object,
 symbol       DASHBNB
 price     0.30330000
 Name: 495, dtype: object,
 symbol        OMGBNB
 price     0.03938000
 Name: 498, dtype: object,
 symbol      MATICBNB
 price     0.00266100
 Name: 503, dtype: object,
 symbol       ATOMBNB
 price     0.04392000
 Name: 506, dtype: object,
 symbol        PHBBNB
 price     0.00013700
 Name: 518, dtype: object,
 symbol      TFUELBNB
 price     0.00012590
 Name: 523, dtype: object,
 symbol        ONEBNB
 price     0.00042710
 Name: 529, dtype: object,
 symbol        FTMBNB
 price     0.00343200
 Name: 535, dtype: object,
 symbol       ALGOBNB
 price     0.00278800
 Name: 545, dtype: object,
 symbol        ERDBNB
 price     0.00083273
 Name: 557, dtype: object,
 symbol       DOGEBNB
 price     0.00015270
 Name: 562, dtype: object,
 symbol       DUSKBNB
 price     0.00118000
 Name: 567, dtype: object,
 symbol       ANKRBNB
 price     0.00028100
 Name: 573, dtype: object,
 symbol        WINBNB
 price     0.00000114
 Name: 581, dtype: object,
 symbol        COSBNB
 price     0.00003441
 Name: 585, dtype: object,
 symbol      COCOSBNB
 price     0.00561000
 Name: 591, dtype: object,
 symbol       TOMOBNB
 price     0.03255000
 Name: 595, dtype: object,
 symbol       PERLBNB
 price     0.00017070
 Name: 599, dtype: object,
 symbol        CHZBNB
 price     0.00073030
 Name: 613, dtype: object,
 symbol       BANDBNB
 price     0.02248000
 Name: 616, dtype: object,
 symbol         BNBBUSD
 price     589.60000000
 Name: 619, dtype: object,
 symbol       BEAMBNB
 price     0.02177000
 Name: 622, dtype: object,
 symbol        XTZBNB
 price     0.00765800
 Name: 625, dtype: object,
 symbol       HBARBNB
 price     0.00054690
 Name: 631, dtype: object,
 symbol        NKNBNB
 price     0.00074700
 Name: 634, dtype: object,
 symbol        STXBNB
 price     0.00314700
 Name: 643, dtype: object,
 symbol       KAVABNB
 price     0.00829000
 Name: 646, dtype: object,
 symbol            BNBNGN
 price     43608.00000000
 Name: 650, dtype: object,
 symbol       ARPABNB
 price     0.00024280
 Name: 652, dtype: object,
 symbol       CTXCBNB
 price     0.00412200
 Name: 662, dtype: object,
 symbol        BCHBNB
 price     0.94200000
 Name: 665, dtype: object,
 symbol            BNBRUB
 price     44759.69000000
 Name: 675, dtype: object,
 symbol       TROYBNB
 price     0.00002219
 Name: 676, dtype: object,
 symbol       VITEBNB
 price     0.00070700
 Name: 682, dtype: object,
 symbol        FTTBNB
 price     0.08070000
 Name: 685, dtype: object,
 symbol           BNBTRY
 price     7661.00000000
 Name: 689, dtype: object,
 symbol          BNBEUR
 price     523.80000000
 Name: 697, dtype: object,
 symbol        OGNBNB
 price     0.00169000
 Name: 701, dtype: object,
 symbol       DREPBNB
 price     0.00009380
 Name: 704, dtype: object,
 symbol        TCTBNB
 price     0.00041860
 Name: 715, dtype: object,
 symbol        WRXBNB
 price     0.00192300
 Name: 718, dtype: object,
 symbol        LTOBNB
 price     0.00248000
 Name: 727, dtype: object,
 symbol      STRATBNB
 price     0.01900000
 Name: 749, dtype: object,
 symbol        MBLBNB
 price     0.00002045
 Name: 753, dtype: object,
 symbol       COTIBNB
 price     0.00064660
 Name: 756, dtype: object,
 symbol    BNBBULLUSDT
 price     57.21000000
 Name: 764, dtype: object,
 symbol    BNBBULLBUSD
 price     58.37000000
 Name: 765, dtype: object,
 symbol    BNBBEARUSDT
 price     58.61000000
 Name: 766, dtype: object,
 symbol    BNBBEARBUSD
 price     57.21000000
 Name: 767, dtype: object,
 symbol       STPTBNB
 price     0.00067000
 Name: 768, dtype: object,
 symbol           BNBZAR
 price     5000.00000000
 Name: 773, dtype: object,
 symbol           BNBBKRW
 price     44687.00000000
 Name: 778, dtype: object,
 symbol        SOLBNB
 price     0.31830000
 Name: 783, dtype: object,
 symbol       BNBIDRT
 price     8580288.00
 Name: 788, dtype: object,
 symbol       CTSIBNB
 price     0.00162100
 Name: 793, dtype: object,
 symbol       HIVEBNB
 price     0.00429000
 Name: 795, dtype: object,
 symbol        CHRBNB
 price     0.00157370
 Name: 798, dtype: object,
 symbol        MDTBNB
 price     0.00073720
 Name: 811, dtype: object,
 symbol       STMXBNB
 price     0.00005136
 Name: 814, dtype: object,
 symbol         IQBNB
 price     0.00002949
 Name: 824, dtype: object,
 symbol          BNBGBP
 price     448.00000000
 Name: 831, dtype: object,
 symbol        DGBBNB
 price     0.00007640
 Name: 833, dtype: object,
 symbol       COMPBNB
 price     5.71900000
 Name: 839, dtype: object,
 symbol       BNBBIDR
 price     8556243.00
 Name: 844, dtype: object,
 symbol        SXPBNB
 price     0.00371200
 Name: 852, dtype: object,
 symbol        SNXBNB
 price     0.01273000
 Name: 855, dtype: object,
 symbol       VTHOBNB
 price     0.00001404
 Name: 864, dtype: object,
 symbol       IRISBNB
 price     0.00166200
 Name: 872, dtype: object,
 symbol        MKRBNB
 price     6.90300000
 Name: 875, dtype: object,
 symbol        DAIBNB
 price     0.04876000
 Name: 879, dtype: object,
 symbol       RUNEBNB
 price     0.01814000
 Name: 883, dtype: object,
 symbol        FIOBNB
 price     0.00033710
 Name: 897, dtype: object,
 symbol       BNBUPUSDT
 price     736.71000000
 Name: 900, dtype: object,
 symbol    BNBDOWNUSDT
 price      0.08155000
 Name: 901, dtype: object,
 symbol        AVABNB
 price     0.00417600
 Name: 904, dtype: object,
 symbol          BNBAUD
 price     833.50000000
 Name: 912, dtype: object,
 symbol        BALBNB
 price     0.42580000
 Name: 914, dtype: object,
 symbol         YFIBNB
 price     82.19000000
 Name: 917, dtype: object,
 symbol          BNBDAI
 price     589.10000000
 Name: 929, dtype: object,
 symbol        JSTBNB
 price     0.00021850
 Name: 932, dtype: object,
 symbol        SRMBNB
 price     0.00852000
 Name: 936, dtype: object,
 symbol        ANTBNB
 price     0.01049000
 Name: 940, dtype: object,
 symbol        CRVBNB
 price     0.00687000
 Name: 944, dtype: object,
 symbol       SANDBNB
 price     0.01029500
 Name: 948, dtype: object,
 symbol      OCEANBNB
 price     0.00187800
 Name: 952, dtype: object,
 symbol        NMRBNB
 price     0.06630000
 Name: 956, dtype: object,
 symbol        DOTBNB
 price     0.05815000
 Name: 960, dtype: object,
 symbol       LUNABNB
 price     0.07340000
 Name: 964, dtype: object,
 symbol        RSRBNB
 price     0.00005920
 Name: 970, dtype: object,
 symbol       PAXGBNB
 price     3.03900000
 Name: 974, dtype: object,
 symbol       WNXMBNB
 price     0.17350000
 Name: 978, dtype: object,
 symbol        TRBBNB
 price     0.51700000
 Name: 982, dtype: object,
 symbol       BZRXBNB
 price     0.00514000
 Name: 990, dtype: object,
 symbol      SUSHIBNB
 price     0.01167000
 Name: 996, dtype: object,
 symbol       YFIIBNB
 price     5.77000000
 Name: 1000, dtype: object,
 symbol        KSMBNB
 price     0.55580000
 Name: 1004, dtype: object,
 symbol       EGLDBNB
 price     0.71180000
 Name: 1008, dtype: object,
 symbol        DIABNB
 price     0.00381300
 Name: 1012, dtype: object,
 symbol        BELBNB
 price     0.00369200
 Name: 1032, dtype: object,
 symbol       WINGBNB
 price     0.04865000
 Name: 1036, dtype: object,
 symbol       SWRVBNB
 price     0.00150400
 Name: 1038, dtype: object,
 symbol      CREAMBNB
 price     0.05970000
 Name: 1046, dtype: object,
 symbol        UNIBNB
 price     0.03230000
 Name: 1048, dtype: object,
 symbol       AVAXBNB
 price     0.18347000
 Name: 1058, dtype: object,
 symbol       BAKEBNB
 price     0.00292100
 Name: 1064, dtype: object,
 symbol     BURGERBNB
 price     0.00614000
 Name: 1065, dtype: object,
 symbol        FLMBNB
 price     0.00333000
 Name: 1068, dtype: object,
 symbol       CAKEBNB
 price     0.02183000
 Name: 1074, dtype: object,
 symbol     SPARTABNB
 price     0.00046510
 Name: 1076, dtype: object,
 symbol        XVSBNB
 price     0.03612000
 Name: 1085, dtype: object,
 symbol      ALPHABNB
 price     0.00149900
 Name: 1089, dtype: object,
 symbol       AAVEBNB
 price     0.38880000
 Name: 1095, dtype: object,
 symbol       NEARBNB
 price     0.01389300
 Name: 1103, dtype: object,
 symbol        FILBNB
 price     0.09480000
 Name: 1111, dtype: object,
 symbol        INJBNB
 price     0.02033000
 Name: 1119, dtype: object,
 symbol        CTKBNB
 price     0.00275800
 Name: 1131, dtype: object,
 symbol       KP3RBNB
 price     1.72990000
 Name: 1143, dtype: object,
 symbol        AXSBNB
 price     0.21300000
 Name: 1145, dtype: object,
 symbol       HARDBNB
 price     0.00167800
 Name: 1149, dtype: object,
 symbol           BNBBRL
 price     3355.00000000
 Name: 1153, dtype: object,
 symbol       UNFIBNB
 price     0.02654000
 Name: 1170, dtype: object,
 symbol       PROMBNB
 price     0.02660000
 Name: 1189, dtype: object,
 symbol       BIFIBNB
 price     2.77700000
 Name: 1347, dtype: object,
 symbol            BNBUAH
 price     16210.00000000
 Name: 1400, dtype: object,
 symbol        ICPBNB
 price     0.06980000
 Name: 1431, dtype: object,
 symbol         ARBNB
 price     0.09128000
 Name: 1442, dtype: object,
 symbol       POLSBNB
 price     0.00602500
 Name: 1446, dtype: object,
 symbol        MDXBNB
 price     0.00111300
 Name: 1450, dtype: object,
 symbol       MASKBNB
 price     0.02885000
 Name: 1453, dtype: object,
 symbol        LPTBNB
 price     0.09569000
 Name: 1457, dtype: object,
 symbol         NUBNB
 price     0.00173710
 Name: 1471, dtype: object,
 symbol        ATABNB
 price     0.00197500
 Name: 1485, dtype: object,
 symbol        GTCBNB
 price     0.03393000
 Name: 1489, dtype: object,
 symbol       TORNBNB
 price     0.08412000
 Name: 1493, dtype: object,
 symbol       KEEPBNB
 price     0.00139280
 Name: 1502, dtype: object,
 symbol        ERNBNB
 price     0.02287000
 Name: 1515, dtype: object,
 symbol       KLAYBNB
 price     0.00221300
 Name: 1519, dtype: object,
 symbol       BONDBNB
 price     0.04375000
 Name: 1532, dtype: object,
 symbol        MLNBNB
 price     0.16910000
 Name: 1536, dtype: object,
 symbol      QUICKBNB
 price     0.52700000
 Name: 1549, dtype: object,
 symbol        C98BNB
 price     0.00495400
 Name: 1553, dtype: object,
 symbol        CLVBNB
 price     0.00190500
 Name: 1556, dtype: object,
 symbol        QNTBNB
 price     0.35280000
 Name: 1560, dtype: object,
 symbol       FLOWBNB
 price     0.01980000
 Name: 1564, dtype: object,
 symbol       MINABNB
 price     0.00773500
 Name: 1572, dtype: object,
 symbol        RAYBNB
 price     0.01612000
 Name: 1575, dtype: object,
 symbol       FARMBNB
 price     0.20930000
 Name: 1579, dtype: object,
 symbol     ALPACABNB
 price     0.00118700
 Name: 1583, dtype: object,
 symbol       MBOXBNB
 price     0.00993000
 Name: 1590, dtype: object,
 symbol       WAXPBNB
 price     0.00112200
 Name: 1602, dtype: object,
 symbol      TRIBEBNB
 price     0.00154200
 Name: 1605, dtype: object,
 symbol        GNOBNB
 price     0.66210000
 Name: 1610, dtype: object,
 symbol       DYDXBNB
 price     0.02088800
 Name: 1625, dtype: object,
 symbol         BNBUSDP
 price     592.15000000
 Name: 1635, dtype: object,
 symbol       GALABNB
 price     0.00107741
 Name: 1640, dtype: object,
 symbol        ILVBNB
 price     2.54600000
 Name: 1650, dtype: object,
 symbol        YGGBNB
 price     0.01151000
 Name: 1655, dtype: object,
 symbol       FIDABNB
 price     0.01249000
 Name: 1670, dtype: object,
 symbol       AGLDBNB
 price     0.00378100
 Name: 1676, dtype: object,
 symbol        RADBNB
 price     0.02768000
 Name: 1680, dtype: object,
 symbol       BETABNB
 price     0.00200650
 Name: 1687, dtype: object,
 symbol       RAREBNB
 price     0.00268600
 Name: 1692, dtype: object,
 symbol      CHESSBNB
 price     0.00486100
 Name: 1709, dtype: object,
 symbol        DARBNB
 price     0.00493476
 Name: 1726, dtype: object,
 symbol        BNXBNB
 price     0.23150000
 Name: 1729, dtype: object,
 symbol        RGTBNB
 price     0.03979000
 Name: 1735, dtype: object,
 symbol       MOVRBNB
 price     0.53990000
 Name: 1744, dtype: object,
 symbol       CITYBNB
 price     0.01910000
 Name: 1748, dtype: object,
 symbol        ENSBNB
 price     0.11521000
 Name: 1752, dtype: object,
 symbol         QIBNB
 price     0.00035280
 Name: 1764, dtype: object,
 symbol      JASMYBNB
 price     0.00029380
 Name: 1782, dtype: object,
 symbol        AMPBNB
 price     0.00010220
 Name: 1785, dtype: object,
 symbol        PLABNB
 price     0.00378200
 Name: 1789, dtype: object]

In [51]:
#np.fill_diagonal(matrix, 1)

In [50]:
#creamos el data frame
#tabla_arg = pd.DataFrame(data = matrix, index = names, columns = names)
#tabla_arg

In [72]:
# tickers_df.info

In [69]:
# lista de los simbolos con los cuales vamos a trabajar y funcion para poder selecionar sus valores a la lista tick
#names = ['XRP', 'BTC', 'ETH', 'USDT', 'USDC', 'XRP', 'ADA', 'BUSD']
#tick = []

#for i in range(1798): #1798 porque es el numero de rows
#    for b in names:
#        if b in tickers_df.iloc[i]['symbol']:
#            tick.append(tickers[i])